import { GoogleGenAI, Modality, Part } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Function to convert a File object to a GoogleGenerativeAI.Part
async function fileToGenerativePart(file: File): Promise<Part> {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        // The result includes the data URL prefix (e.g., "data:image/png;base64,"), 
        // which should be removed.
        resolve(reader.result.split(',')[1]);
      } else {
        // Fallback for ArrayBuffer or other types, though less common for this use case
        resolve('');
      }
    };
    reader.readAsDataURL(file);
  });

  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
}

export const generateProductImage = async (
  productImage: File,
  prompt: string,
  swapImage: File | null,
  aspectRatio: string = "1:1",
  qualitySettings: { detail: number, artistic: number, noise: number } = { detail: 5, artistic: 5, noise: 5 }
): Promise<string> => {
  const model = 'gemini-2.5-flash-image';
  
  const productImagePart = await fileToGenerativePart(productImage);
  
  // Construct quality sub-prompts
  let qualityPrompt = "";
  if (qualitySettings.detail > 7) qualityPrompt += ", ultra-high definition, razor-sharp details, intricate textures";
  else if (qualitySettings.detail < 3) qualityPrompt += ", soft focus, minimalist detail";

  if (qualitySettings.artistic > 7) qualityPrompt += ", heavy cinematic lighting, dramatic artistic style, highly stylized";
  else if (qualitySettings.artistic < 3) qualityPrompt += ", natural lighting, realistic documentary style";

  if (qualitySettings.noise > 7) qualityPrompt += ", perfectly smooth surface, clean render, zero grain";

  const textPart = { text: `${prompt}. The output image must have an aspect ratio of ${aspectRatio}${qualityPrompt}.` };

  const parts: Part[] = [productImagePart];

  if (swapImage) {
    const swapImagePart = await fileToGenerativePart(swapImage);
    parts.push(swapImagePart);
  }
  
  parts.push(textPart);

  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: parts,
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  // Extract the image data from the response
  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
};

export const analyzeImage = async (image: File, customPrompt?: string): Promise<{ objects: string[], description: string }> => {
  const imagePart = await fileToGenerativePart(image);
  const defaultPrompt = "Analyze this product image. Provide a list of objects detected and a brief professional description for marketing. Return the result in JSON format like this: {\"objects\": [\"object1\", \"object2\"], \"description\": \"...\"}";
  const prompt = customPrompt || defaultPrompt;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: { parts: [imagePart, { text: prompt }] }
  });

  const text = response.text;
  
  if (!text) {
    throw new Error("No text response from Gemini.");
  }

  try {
    // Clean up potential markdown formatting in the response
    const jsonString = text.replace(/```json/g, '').replace(/```/g, '').trim();
    return JSON.parse(jsonString);
  } catch (e) {
    console.error("Failed to parse analysis JSON:", text);
    return {
      objects: ["منتج"],
      description: text || "وصف غير متوفر حالياً"
    };
  }
};

export const removeBackground = async (productImage: File): Promise<string> => {
  const imagePart = await fileToGenerativePart(productImage);
  const prompt = "Isolate the main product from this image. Place it on a solid, perfectly white, clean studio background with soft natural shadows at the base. Remove all other objects, hands, or background elements. Keep only the product itself.";

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: {
      parts: [imagePart, { text: prompt }],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("Failed to isolate product.");
};
